import praw
import pandas as pd
import csv
reddit = praw.Reddit(client_id='W3-I1X1bwAReFOsYtNQdww', client_secret='5nDES6wvXY6dsETvJJOg3Zkke9KCHQ', user_agent='chaithra')

header = ['rowid','title', 'score', 'id', 'subreddit', 'url', 'num_comments', 'body', 'created']
with open('my_csv.csv', 'w', encoding='UTF8') as f:
    writer = csv.writer(f)
    # write the header
    writer.writerow(header)

reddits = ['apolloapp','Buddhism','destiny2','Moviesinthemaking','thedivision','HadToHurt','wowthissubexists',
'bertstrips','BonerMaterial','beetlejuicing','ihavesex','socialism','wtfstockphotos','TalesFromYourServer','Nootropics',
'popping','Aquariums','NoMansSkyTheGame','Military','badtattoos','HailCorporate','MrRobot','Outdoors','Conservative',
'OverwatchUniversity','SexInFrontOfOthers','restofthefuckingowl','ukpolitics','succulents','mallninjashit','amateurcumsluts',
'architecture','CollegeAmateurs','tech','golf','TrueAskReddit','wholesomegifs','puns','Bondage','funsized','Monero','Kanye',
'JapanTravel','CatTaps','radiohead','Terraria','Bad_Cop_No_Donut','GoneWildPlus','darkjokes','copypasta','mildlypenis',
'knitting','bestoflegaladvice','EliteDangerous','MEOW_IRL','starcitizen','TooMeIrlForMeIrl','cumfetish','weightroom',
'montageparodies','InteriorDesign','YouSeeComrade','JoeRogan','fakealbumcovers','Exxxtras','absolutelynotme_irl','thegrandtour',
'CasualUK','androidapps','AmateurRoomPorn','JiggleFuck','antiMLM','lastimages','india','betterCallSaul','AccidentalComedy',
'SexyFrex','realasians','Gonewild18','selfimprovement','churning','StonerEngineering','cableporn','knives','HugeDickTinyChick',
'boltedontits','marijuanaenthusiasts','budgetfood','fatpeoplestories','girlskissing','Pizza','AndroidGaming','findareddit',
'gifsgonewild','singapore','AnimalCrossing','svenskpolitik','homegrowntits','diablo3','WouldYouFuckMyWife','techsupportmacgyver',
'ClashOfClans','Innie','Animemes','FashionReps','runescape','Smite','bdsm','swedishproblems','NHLStreams','Punny','learnpython',
'smallbusiness','AnalGW','TinyHouses','languagelearning','BitcoinMarkets','Amd','deepthroat','musictheory','japan','dogecoin',
'simpleliving','Nsfw_Amateurs','Windows10','stevenuniverse','dirtypenpals','dirtyr4r','Catloaf','linguistics','GlobalOffensiveTrade',
'Seattle','ActualPublicFreakouts','Archero','ArchitecturalRevival','AreTheStraightsOK','Ayahuasca','BBW','BobsTavern','CODWarzone',
'COVID19','COVID19_support','Californiahunting','ChangingRooms','China_Flu','CompetitiveTFT','CoronaVirus_2019_nCoV','Coronavirus',
'CoronavirusMemes','CoronavirusUK','CoronavirusUS','Damn_Homie__','DankLeft','DestructionPorn','DownUnderTV','DragonRajaMobile',
'Eldenring','ExtremeCarCrashes','FearMe','ForeverAlone','GachaLifeCringe','Galaxy_S20','GirlsDoLawsuits','HENTAI_GIF','Home',
'HorriblyDepressing','Hunting','HydroHomies','HypixelSkyblock','IllegallySmolCats','ImmortalTaoist','JOIP','LSA','LifeAfterNarcissism',
'LoveIsBlindOnNetflix','MDMA','MWLoadouts','MakeMeSuffer','MemantineHCl','Motorcyclecrash','Natureisbrutal','NoahGetTheBoat',
'PCRedDead','PandemicPreps','PerkByDaylight','PresidentialRaceMemes','RLCraft','RoyalDice','SSAwakening','SaintSeiyaKOTZ','Salvia',
'SneakySasquatch','Stoner','SuperModelIndia','SwShLeaks','TeamfightTactics','Tiktokhelp','UlalaIdleAdventure','VALORANT','Vindicta',
'WhyWouldYouFuckThat','YouFellForItFool','abusesurvivors','ac_newhorizons','addiction','alcoholicsanonymous','alcoholism','boobs',
'braceface','carcrash','chubby','cleancarts','cleavage','cocaine','cuckoldcaptions','cursedimages','domesticviolence','ecchi',
'facesitting','help','iWantToFuckHer','ketamine','leaves','mdmatherapy','mescaline','meth','microdosing','microgrowery',
'modernwarfare','morbidcuriosity','necromancy','noids','nsfwasmr','passionx','picsofdeadwhalebait','rape','saplings','seethru',
'shoptitans','shroomers','superheroporn','underlords','weedstocks','AHADatl','AraAra','burstingout','funny','AskReddit','todayilearned',
'worldnews','science','pics','gaming','IAmA','videos','movies','Music','blog','gifs','news','explainlikeimfive','askscience','EarthPorn',
'books','television','mildlyinteresting','LifeProTips','Showerthoughts','space','DIY','Jokes','gadgets','nottheonion','sports','tifu',
'food','photoshopbattles','Documentaries','dataisbeautiful','UpliftingNews','Futurology','history','GetMotivated','listentothis','personalfinance',
'OldSchoolCool','Art','philosophy','WritingPrompts','nosleep','creepy','TwoXChromosomes','Fitness','technology','WTF','bestof','AdviceAnimals','politics',
'atheism','interestingasfuck','woahdude','europe','BlackPeopleTwitter','oddlysatisfying','leagueoflegends','gonewild','reactiongifs',
'pcmasterrace','wholesomememes','gameofthrones','Unexpected','facepalm','Overwatch','lifehacks','Android','trees','me_irl','relationships',
'Games','nba','Whatcouldgowrong','programming','NatureIsFuckingLit','dankmemes','tattoos','memes','CrappyDesign','malefashionadvice','soccer',
'travel','cringepics','comics','AnimalsBeingJerks','sex','pokemon','NSFW_GIF','HistoryPorn','4chan','mildlyinfuriating','Tinder','RealGirls',
'StarWars','buildapc','Frugal','FoodPorn','instant_regret','GifRecipes','OutOfTheLoop','PS4','AnimalsBeingBros','Eyebleach','loseit','Bitcoin',
'YouShouldKnow','pokemongo','nonononoyes','trippinthroughtime','RoastMe','rickandmorty','hiphopheads','HighQualityGifs','wheredidthesodago','nfl',
'AskHistorians','cringe','RoomPorn','Cooking','FiftyFifty','dadjokes','xboxone','hearthstone','trashy','holdmybeer','baseball','Damnthatsinteresting',
'EatCheapAndHealthy','quityourbullshit','youtubehaiku','anime','hmmm','iamverysmart','CryptoCurrency','cats','bodyweightfitness','PeopleFuckingDying','humor',
'apple','GlobalOffensive','itookapicture','conspiracy','scifi','BetterEveryLoop','holdthemoan','Wellthatsucks','pcgaming','MovieDetails','thatHappened','streetwear',
'comicbooks','Minecraft','AbandonedPorn','boardgames','oldpeoplefacebook','freebies','rarepuppers','shittyaskscience','howto','BikiniBottomTwitter','keto','wow',
'woodworking','educationalgifs','MadeMeSmile','PUBATTLEGROUNDS','nevertellmetheodds','NintendoSwitch','reallifedoodles','AskMen','NetflixBestOf','PrequelMemes',
'changemyview','photography','cars','MealPrepSunday','gardening','hockey','learnprogramming','BeAmazed','spaceporn','ChildrenFallingOver','PerfectTiming','AskWomen',
'iphone','slowcooking','blackmagicfuckery','BustyPetite','MakeupAddiction','GameDeals','FortNiteBR','HumansBeingBros','JusticePorn','battlestations','DunderMifflin','recipes',
'investing','relationship_advice','DestinyTheGame','therewasanattempt','frugalmalefashion','talesfromtechsupport','MMA','ProgrammerHumor','madlads','NoStupidQuestions',
'SkincareAddiction','skyrim','MemeEconomy','natureismetal','Steam','offmychest','nintendo','nsfw_gifs','DnD','AnimalsBeingDerps','nononono','ATBGE','GamePhysics','ContagiousLaughter',
'gentlemanboners','whatisthisthing','dogs','thewalkingdead','confession','youseeingthisshit','insanepeoplefacebook','urbanexploration','MurderedByWords','firstworldanarchists',
'wallpapers','FanTheories','geek','WhitePeopleTwitter','MapPorn','starterpacks','Roadcam','OSHA','Economics','Amateur','niceguys','femalefashionadvice','BuyItForLife','math',
'entertainment','KenM','thisismylifenow','asoiaf','Awwducational','cumsluts','meirl','LearnUselessTalents','DotA2','TalesFromRetail','UNBGBBIIVCHIDCTIICBG','savedyouaclick',
'OopsDidntMeanTo','CampingandHiking','harrypotter','teenagers','electronicmusic','CozyPlaces','writing','running','wallpaper','UnethicalLifeProTips','raspberry_pi','TrueReddit',
'polandball','PetiteGoneWild','Entrepreneur','Drugs','motorcycles','olympics','shutupandtakemymoney','business','TumblrInAction','ProRevenge','Fallout','shittyfoodporn',
'GirlsFinishingTheJob','RocketLeague','pettyrevenge','TrollXChromosomes','nostalgia','legaladvice','environment','Sneakers','ExpectationVsReality','MaliciousCompliance',
'Justrolledintotheshop','ArtisanVideos','whitepeoplegifs','babyelephantgifs','CFB','DoesAnybodyElse','westworld','progresspics','evilbuildings','calvinandhobbes',
'StartledCats','ANormalDayInRussia','JusticeServed','ass','QuotesPorn','guns','IdiotsFightingThings','DeepIntoYouTube','ShittyLifeProTips','PoliticalHumor','breakingbad',
'financialindependence','AccidentalRenaissance','UnresolvedMysteries','coolguides','chemicalreactiongifs','outside','Rainbow6','justneckbeardthings','Guitar','blunderyears','AsiansGoneWild','offbeat','socialskills',
'assholedesign','carporn','ofcoursethatsathing','buildapcsales','psychology','canada','standupshots','ColorizedHistory','porninfifteenseconds','backpacking','h3h3productions',
'tipofmytongue','CasualConversation','zelda','ethereum','HomeImprovement','DesignPorn','LegalTeens','SubredditDrama','bodybuilding','Cinemagraphs','INEEEEDIT','freefolk','adorableporn',
'everymanshouldknow','southpark','depression','creepyPMs','youdontsurf','Astronomy','LetsNotMeet','beta','milf','iamverybadass','rule34','IASIP','PenmanshipPorn','WatchPeopleDieInside',
'SquaredCircle','IWantToLearn','beer','greentext','Celebs','FellowKids','horror','2meirl4meirl','CrazyIdeas','tumblr','Physics','DiWHY','CityPorn','Marvel','OnOff','formula1',
'Justfuckmyshitup','lego','marvelstudios','BiggerThanYouThought','PublicFreakout','SweatyPalms','corgi','holdmycosmo','WhyWereTheyFilming',
'shittyrobots','Boobies','ChoosingBeggars','foodhacks','NotMyJob','web_design','Design','HappyEmbarrassedGirls','NoFap','WatchItForThePlot','hacking',
'jailbreak','CatastrophicFailure','ThriftStoreHauls','Twitch','StrangerThings','blackpeoplegifs','de_IAmA','fantasyfootball','circlejerk','likeus','futurama',
'worldpolitics','theydidthemath','getdisciplined','boottoobig','NSFWFunny','Shitty_Car_Mods','60fpsporn','linux','homemadexxx','sadcringe','pawg','powerwashingporn',
'doctorwho','combinedgifs','minimalism','mechanical_gifs','dirtysmall','NSFW_Snapchat','WeAreTheMusicMakers','softwaregore','TittyDrop','drawing','vinyl',
'Fantasy','DepthHub','LipsThatGrip','surrealmemes','Perfectfit','indianpeoplefacebook','fakehistoryporn','PewdiepieSubmissions','yesyesyesyesno',
'LateStageCapitalism','WeWantPlates','collegesluts','Meditation','girlsinyogapants','kpop','StoppedWorking','howtonotgiveafuck',
'celebnsfw','TheSilphRoad','MorbidReality','shittyreactiongifs','manga','Parenting','Watches','ScottishPeopleTwitter','smashbros',
'Filmmakers','nsfwhardcore','seduction','dankchristianmemes','MachineLearning','thalassophobia','cosplaygirls','Zoomies','gonewildcurvy',
'gifsthatkeepongiving','Health','ComedyCemetery','DadReflexes','PoliticalDiscussion','MechanicalKeyboards','indieheads','bicycling',
'graphic_design','MURICA','totallynotrobots','malelivingspace','netflix','hardware','gatekeeping','crappyoffbrands','asstastic',
'techsupportgore','xxfitness','Pareidolia','crafts','worldbuilding','gamedev','truegaming','startups','EmpireDidNothingWrong','nasa',
'FloridaMan','google','Blowjobs','PandR','im14andthisisdeep','AMA','spacex','wallstreetbets','netsec','disneyvacation','beermoney',
'CollegeBasketball','javascript','teslamotors','CatsStandingUp','TrollYChromosome','perfectloops','raisedbynarcissists','palegirls',
'3DS','dating_advice','KerbalSpaceProgram','magicTCG','fullmoviesonyoutube','self','SubredditSimulator','Metal','AnimalTextGifs','ActLikeYouBelong',
'Bossfight','sysadmin','LivestreamFail','Cyberpunk','Python','Prematurecelebration','IDontWorkHereLady','redditgetsdrawn','nsfwcosplay','fo4','civ',
'stocks','holdmyjuicebox','curvy','ThingsCutInHalfPorn','GWCouples','childfree','pornvids','happy','trashyboners','TheLastAirbender','hentai',
'biology','Simulated','Glitch_in_the_Matrix','cordcutters','anime_irl','StraightGirlsPlaying','NeutralPolitics','audiophile','holdmyfries',
'aviation','camping','freeuse','techsupport','AccidentalWesAnderson','redheads','ketorecipes','britishproblems','thick','somethingimade',
'Homebrewing','Foodforthought','misleadingthumbnails','AsianHotties','edmproduction','FunnyandSad','Libertarian','RetroFuturism','drunk','ginger',
'jesuschristreddit','juicyasians','GirlswithGlasses','theocho','rage','witcher','FestivalSluts','webdev','wikipedia','TinyTits','SandersForPresident',
'tippytaps','gonewildstories','australia','podcasts','TheDepthsBelow','Survival','MonsterHunter','literature','workgonewild','holdmyredbull',
'chemistry','TheSimpsons','GoneWildTube','EngineeringPorn','thenetherlands','privacy','lgbt','mac','astrophotography','rpg','ArchitecturePorn',
'starcraft','IdiotsInCars','wiiu','2007scape','AsianBeauty','homestead','JUSTNOMIL','dogpictures','solotravel','lotr','battlefield_one',
'cosplay','dank_meme','dontdeadopeninside','Graffiti','btc','shortscarystories','fatlogic','delusionalartists','confusing_perspective',
'sweden','litecoin','tf2','ArtefactPorn','hiking','tightdresses','ArcherFX','TrumpCriticizesTrump','WhatsWrongWithYourDog',
'hitmanimals','nutrition','Piracy','notinteresting','WatchandLearn','rearpussy','roosterteeth','wifesharing','Coffee',
'heroesofthestorm','PrettyGirls','LucidDreaming','batman','EDM','unitedkingdom','LadyBoners','patientgamers',
'4PanelCringe','anal','pussy','lesbians','GrandTheftAutoV','darksouls3','grool','outrun','TheWayWeWere','DecidingToBeBetter',
'Hotchickswithtattoos','ExposurePorn','france','mashups','ImaginaryLandscapes','productivity','Paranormal','TopGear','vegan',
'ethtrader','Ripple','MachinePorn','quiver','FreeEBOOKS','SketchDaily','climbing','firstworldproblems','woof_irl','facedownassup',
'classicalmusic','3Dprinting','ClashRoyale','WastedGifs','engineering','specializedtools','gamernews','bonehurtingjuice','Breath_of_the_Wild',
'porn_gifs','adventuretime','randomsexiness','gonewildaudio','MostBeautiful','SequelMemes','DCcomics','ArtPorn','MensRights','vandwellers','HumanPorn',
'dogswithjobs','StardewValley','2healthbars','suicidegirls','pussypassdenied','O_Faces',
'ffxiv','MyPeopleNeedMe','MilitaryPorn','Guildwars2','gif','ShouldIbuythisgame','community',
'halo','ADHD','Unashamed','breathinginformation','whowouldwin','blackmirror','medicine','1200isplenty',
'Diablo','jobs','WeatherGifs','altgonewild','snowboarding','bodyperfection','Anxiety','Superbowl','Warframe',
'Stacked','NSFW_HTML5','ImaginaryMonsters','birdswitharms','EDC','PropagandaPosters','porn','brasil','Frisson',
'mealtimevideos','rupaulsdragrace','datgap','IWantOut','dbz','Competitiveoverwatch','forwardsfromgrandma','ireland',
'darksouls','Baking','headphones','startrek','hardcoreaww','Autos','tipofmypenis','raining','pathofexile','Fishing',
'catpranks','gettingherselfoff','Hotwife','nsfwoutfits','summonerschool','AskOuija','HighResNSFW','OnePiece','Boxing',
'NSFW411','quotes','electronic_cigarette','cscareerquestions','photocritique','CombatFootage','BeforeNAfterAdoption',
'r4r','Screenwriting','FORTnITE','LSD','homeautomation','analog','Psychonaut','masseffect','asmr','yoga','vexillology',
'finance','FIFA','AntiJokes','Badfaketexts','skateboarding','CuteModeSlutMode','gamegrumps','gonewild30plus','hugeboobs',
'creepyasterisks','beards','yesyesyesno','creampies','arresteddevelopment','CitiesSkylines','Blep','GWNerdy','digitalnomad',
'StarWarsBattlefront','fitgirls','Christianity','terriblefacebookmemes','BigBoobsGW','Sneks','AdrenalinePorn','awwwtf',
'suggestmeabook','wholesomebpt','whenitgoesin','trebuchetmemes','skiing','Philippines','gundeals','holdmycatnip','jilling',
'theratio','boobbounce','lewronggeneration','VaporwaveAesthetics','nyc','TrueFilm','answers','AskCulinary','Naruto','PUBG',
'webcomics','instantkarma','NSFW_Japan','hardbodies','simps','newzealand','casualiama','RandomActsOfBlowJob','Upskirt',
'GoneMild','CryptoMarkets','elderscrollsonline','BoJackHorseman','gonewildcolor','gainit','funhaus','Idubbbz','youtube']

for i in reddits:
    posts = []
    ml_subreddit = reddit.subreddit(i)
    for post in ml_subreddit.hot(limit=10):
        posts.append([post.title, post.score, post.id, post.subreddit, post.url, post.num_comments, post.selftext, post.created])
    posts = pd.DataFrame(posts,columns=['title', 'score', 'id', 'subreddit', 'url', 'num_comments', 'body', 'created'])
    
    posts.to_csv('raw_extract.csv', mode='a', header=False)
